### ISSUE TITLE
Make tool available as a python package?

### ISSUE THREAD

**Issue by susannasiebert** [GfellerLab/MixMHC2pred#1]
Our team is interested in integrating MixMHC2pred into pVACtools. I'm not sure what language it was written in but we were wondering if there are any plans of making it available as a python package?

**Comment by dagfeller** [comment]
Hi. Thank you for your interest in using our tool in pVACtools. Although we would consider having it part of pVACtools in the future, we cannot offer this possibility right now, since the paper is not officially published, and we have decided to wait until official publication before allowing others to use it in their pipelines. Also, we need to draw your attention that MixMHC2pred is under license for commercial usage, so non-academic users of pVAC are required to buy the MixMHC2pred license (I guess the same applies to NetMHC).
