### ISSUE TITLE
Cutoff selection of %Rank score when predicting HLA-II neo-peptide using MixMHC2pred

### ISSUE THREAD

**Issue by ChiZhou-SITI** [GfellerLab/MixMHC2pred#2]
Hi, we want to use MixMHC2pred to predict candidate HLA-II neo-peptide from NGS data. As you mentioned in README "The score returned (%Rank, column 3) corresponds to a percentile rank (best score is 0, worst score is 100)". Could you please give any advice on how to select the cutoff (like 50 or 95) to ensure both the specificity and sensitivity? Thank you!

**Comment by jracle85** [comment]
Hi,

Thank you for your interest in our tool.

As mentioned, this score corresponds to a percentile rank against random peptides and the lowest value is the best. Concerning the *best* value to use as a cutoff, there is no strict answer, but usually strong HLA-II binders would have a score below 1-2%, but there are still weak binders found with scores of 5-10%.

If you take for example a threshold of 2, you'll usually have a precision > 90% and a recall between 70% - 90%. Please note that these precision/recall values describe if a peptide is presented on the HLA-II or not. But many of the presented peptides will not be immunogenic: other factors come also into play (e.g. the recognition by the CD4+ T cells). Thus the precision (and possibly recall) would be different if the question is about immunogenic epitopes. However, from our analyses we can note that selecting the best scoring peptides from our predictor is a good starting point in order to enrich this candidate set to have as many true epitopes as possible, but you should then further test these candidates experimentally because multiple of them would nevertheless still be negative for various reasons.

So, what threshold value to use will also depend on what you can afford, how many candidates you can test. Another strategy than having a fix cutoff value is thus to select the best X candidates after ranking them by their score.

I hope this helps. Best regards,

Julien

**Comment by ChiZhou-SITI** [comment]
Hi, Julien,

Thank you for your kind and clear reply!  It really helps.
We just have another question about the alleles, we noticed that there are only 39 alleles in Alleles_list.txt, so if the HLA-II types identified from NGS data were not included in this list, could the score be calculated?

Thank you so much!
Chi

**Comment by jracle85** [comment]
Hi Chi,

For the moment, our predictor indeed includes 38 alleles. Other alleles will be added once data is available.

Our predictor is currently not pan-specific and thus it can only do predictions for those alleles on which it was trained. Nevertheless it includes a large coverage of HLA-DR and DP alleles, with the most frequent alleles certainly defined.

If you have a sample containing another allele, I would suggest analyzing your data in one of these ways:

* if you're interested to get a list of best candidate antigens (maybe to test them experimentally and find some immunogenic epitopes), you could consider the predictions on the remaining alleles defined in MixMHC2pred. This would restrict you to a subset of alleles but anyway a same epitope is likely not binding to multiple different alleles. There should thus still be some good candidates remaining.

* if you really want to include all of your alleles, you could try considering another allele with the same first 3 digits (e.g. DRB1\*04:01 if you want to do predictions for DRB1\*04:02). The binding motifs won't be exactly the same but they will still likely be highly similar such that most peptides presented by the first allele are also likely presented by the other one.

Best regards,

Julien

**Comment by ChiZhou-SITI** [comment]
Thanks a lot! Looking forward to the allele update.
