### ISSUE TITLE
Position of mutation and length of peptides

### ISSUE THREAD

**Issue by wt12318** [GfellerLab/MixMHC2pred#5]
Dear author(s),

When I using this tool, I encounter a problem：
If the mutated amino acid is at the end of the peptide, how should the length of the inputed peptide be selected? Because the input length of the software is limited to 12-25 amino acids, if I select the 9-length peptide upstream of the mutated amino acid, the software will report an NA, but select more than 9-length peptide upstream of the mutated amino acid (for example,12-length peptide), the 9 first amino acids will not contain the mutated amino acid.

Could you give some suggestions?
Best regards

**Comment by jracle85** [comment]
Dear @wt12318 ,

Thank you for your message.

Indeed, very short peptides currently return NA values because there are only very few HLA-II ligands of such sizes. Most of those observed ones in peptidomics data are in fact HLA-I contaminants and not true HLA-II ligands.

So yes, it would be better to take a 12-mer (or longer) peptide, even if the mutation lies at the end of the peptide. I don't understand what is your issue with having the 9 first amino acids that don't contain the mutated amino acid? This would be like that also in real-life situation.

Best regards,

Julien

**Comment by wt12318** [comment]
Dear Julien.

Thank you for your reply.
What I want to expressed is that when the mutation happen in the end of the peptide, the first three offsets would not contain mutation amino acid.
![image-20200608160407957](https://picgo-wutao.oss-cn-shanghai.aliyuncs.com/img/image-20200608160407957.png)

Best regards,

Wutao

**Comment by jracle85** [comment]
Dear Wutao,

Yes, that's a possibility, but it can also happen when having e.g. an 20-mer peptide even if the mutation is near the middle.

But please bear in mind that what is presented by the HLA-II is the "full peptide" (12-mer or longer), so there is a possibility that the amino acids outside of the bound 9-mer core are still seen by the CD4+ T cell and could also play a role in immune recognition (it is likely more the 9-mer core that has importance, but maybe the rest could play also a role).

Otherwise, what you could do if you assume that the mutation must lie in the 9-mer core to be possibly immunogenic would be to do the prediction on the 12-mer (or else) and check afterwards if the mutation is part of the predicted binding core (as returned by MixMHC2pred) - if it isn't you could just reject this peptide.

Cheers,

Julien

**Comment by wt12318** [comment]
Thanks a lot!
